INSERT INTO disasters
    (article_date, image, location, headline, article_link, type, summary)
VALUES
    ("2019-11-02", "http://sa-mcp.s3.amazonaws.com/up-image/D34/9B3/D349B39CE04F47AEA8141C50002244B7.jpg",
        "North Dakota",
        "Portion of Keystone Pipeline shut down after 380,000-gallon oil leak in North Dakota",
        "https://www.usatoday.com/story/news/nation/2019/11/01/keystone-pipeline-leak-oil-spilled-north-dakota/4121954002/",
        "Oil Spill",
        "Pipeline owner TC Energy said Thursday that an estimated 9,120 barrels of oil spilled near Edinburg, North Dakota, affecting 22,500 square feet of wetlands about an hour from the Canadian border..."),
    ("2020-01-17",
        "https://1.bp.blogspot.com/-7Y7VbEQJWWk/XiFlpY8PQuI/AAAAAAAAs9o/LuXhl6wYO2gZ1BfVJqK1IGAofcpCooMCgCLcBGAsYHQ/s1600/2017_0717fukushima.jpg",
        "Japan",
        "TEPCO says new leak has spilt 20,000 litres of radioactive coolant at the stricken Fukushima Nuclear Plant: It is now almost 7 years since Prime Minister Shinzo Abe declared everything is 'under control'",
        "https://www.thebigwobble.org/2020/01/tepco-says-new-leak-has-spilled-20000.html",
        "Radiation Leak",
        "Tokyo Electric Power Company says coolant has seeped out from an underground frozen soil wall built around its crippled Fukushima Daiichi nuclear plant. The frozen soil wall came into operation four years ago. It was built to keep groundwater from flowing into reactor buildings. They were damaged by the March 2011 earthquake, tsunami and subsequent nuclear meltdowns..."),
    ("2020-05-04",
        "https://www.nationalgeographic.com/animals/2020/05/asian-giant-hornets-arrive-united-states/#/01-asian-giant-hornet-minden_00405319.jpg",
        "USA",
        "Murder hornets' have arrived in the U.S.—here's what you should know",
        "https://www.nationalgeographic.com/animals/2020/05/asian-giant-hornets-arrive-united-states/",
        "Invasive Species",
        "Update on May 29, 2020: Washington State officials have confirmed the discovery of a third Asian giant hornet, almost certainly a queen, found dead on a road near Custer, Washington. This likely means a colony was present in the state in fall 2019, and that it produced many queens. These large females lie dormant over the winter, and a small percentage are likely to create successful nests..."),
    ("2020-03-02",
        "https://disasterscharter.org/image/journal/article.jpg?img_id=4719396&t=1583314909457",
        "United Arab Emirates",
        "https://disasterscharter.org/web/guest/activations/-/article/oil-spill-in-united-arab-emirates-activation-645-",
        "Oil Spill",
        " An oil spill has reached the shores of Fujairah, United Arab Emirates with around 1.5 km of coastline being affected. The cause of the oil spill is currently unknown. The full extent of the oil spill and its potential impact is being assessed..."),
    ("2019-10-31",
        "https://www.pexels.com/photo/white-and-gray-cat-in-brown-woven-basket-1543793/",
        "Egypt",
        "https://www.cbsnews.com/news/cats-invasive-species-in-your-backyard-cbsn-originals/",
        "Invasive Species",
        "Cat ipsum dolor sit amet, ears back wide eyed head nudges leave hair on owner's clothes slap kitten brother with paw. Purr leave dead animals as gifts i show my fluffy belly but it's a trap! if you pet it i will tear up your hand or cats are the world pushed the mug off the table. Have my breakfast spaghetti yarn sleep everywhere, but not in my bed white cat sleeps on a black shirt more napping, more napping all the napping is exhausting eat too much then proceed to regurgitate all over living room carpet while humans eat dinner sit and stare."),
    ("2019-10-31",
        "https://www.pexels.com/photo/photo-of-grey-tabby-kitten-lying-down-2558605/",
        "USA",
        "https://www.cbsnews.com/news/cats-invasive-species-in-your-backyard-cbsn-originals/",
        "Invasive Species",
        "Fat baby cat best buddy little guy i could pee on this if i had the energy and snuggles up to shoulders or knees and purrs you to sleep for kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment. Run in circles ooh, are those your $250 dollar sandals? lemme use that as my litter box sleep nap curl up and sleep on the freshly laundered towels pet me pet me don't pet me purr."),
    ("2019-10-31",
        "https://www.pexels.com/photo/short-furred-white-and-brown-tabby-cat-2870353/",
        "France",
        "https://www.cbsnews.com/news/cats-invasive-species-in-your-backyard-cbsn-originals/",
        "Invasive Species",
        "That box? i can fit in that box kitten is playing with dead mouse for rub face on owner yet lick the curtain just to be annoying plays league of legends for cuddle no cuddle cuddle love scratch scratch. Instantly break out into full speed gallop across the house for no reason chase the pig around the house. Meow meow dont wait for the storm to pass."),
    ("2019-10-31",
        "https://www.pexels.com/photo/short-furred-white-and-brown-tabby-cat-2870353/",
        "France",
        "https://www.cbsnews.com/news/cats-invasive-species-in-your-backyard-cbsn-originals/",
        "Invasive Species",
        "Nap all day meow in empty rooms fall asleep on the washing machine for i just saw other cats inside the house and nobody ask me before using my litter box human is behind a closed door, emergency! abandoned! meeooowwww!!! for decide to want nothing to do with my owner today. Purrr purr littel cat, little cat purr purr disappear for four days and return home with an expensive injury; bite the vet or munch, munch, chomp, chomp for destroy house in 5 seconds cats are fats i like to pets them they like to meow back."),
    ("2019-10-31",
        "https://www.pexels.com/photo/short-furred-white-and-brown-tabby-cat-2870353/",
        "France",
        "https://www.cbsnews.com/news/cats-invasive-species-in-your-backyard-cbsn-originals/",
        "Invasive Species",
        "Meow in empty rooms what the heck just happened, something feels fishy ask for petting for kitty power, but cat not kitten around please let me outside pouty face yay! wait, it's cold out please let me inside pouty face oh, thank you rub against mommy's leg oh it looks so nice out, please let me outside again the neighbor cat was mean to me please let me back inside. Cat not kitten around i can haz."),
    ("2019-10-31",
        "https://www.pexels.com/photo/short-furred-white-and-brown-tabby-cat-2870353/",
        "France",
        "https://www.cbsnews.com/news/cats-invasive-species-in-your-backyard-cbsn-originals/",
        "Invasive Species",
        "Chase the pig around the house taco cat backwards spells taco cat so stare at the wall, play with food and get confused by dust but munch, munch, chomp, chomp. When in doubt, wash wack the mini furry mouse or cats are the world. Dont wait for the storm to pass, dance in the rain trip on catnip, wake up human for food at 4am, for twitch tail in permanent irritation cats woo. Kitty power open the door, let me out, let me out, let me-out, let me-aow, let meaow, meaow!");
